spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        create_empty_composites:
          enabled: true